/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'timestamp' : Time,
}
export interface Notification {
  'id' : bigint,
  'kind' : string,
  'read' : boolean,
  'timestamp' : Time,
  'fromUser' : Principal,
  'targetId' : bigint,
}
export interface PostDTO {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
  'comments' : Array<Comment>,
}
export interface Profile {
  'bio' : string,
  'displayName' : string,
  'interests' : string,
  'education' : string,
  'website' : string,
  'coverPhoto' : [] | [ExternalBlob],
  'birthday' : string,
  'gender' : string,
  'favSongs' : string,
  'thoughts' : string,
  'favMovies' : string,
  'location' : string,
  'hobbies' : string,
  'avatar' : [] | [ExternalBlob],
  'relationshipStatus' : string,
}
export interface Story {
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRequest' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commentOnPost' : ActorMethod<[bigint, string], undefined>,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'createProfile' : ActorMethod<[Profile], undefined>,
  'createStory' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'follow' : ActorMethod<[Principal], undefined>,
  'getAllPosts' : ActorMethod<[], Array<PostDTO>>,
  'getAllProfiles' : ActorMethod<[], Array<[Principal, Profile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getFriends' : ActorMethod<[], Array<Principal>>,
  'getMatches' : ActorMethod<[], Array<Principal>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPostsByUser' : ActorMethod<[Principal], Array<PostDTO>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getStarsReceived' : ActorMethod<[], bigint>,
  'getStories' : ActorMethod<[Principal], Array<Story>>,
  'getStoryHighlights' : ActorMethod<[Principal], Array<Story>>,
  'getTinderQueue' : ActorMethod<[], Array<Profile>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'saveStoryToHighlight' : ActorMethod<[bigint], undefined>,
  'searchUsers' : ActorMethod<[string], Array<[Principal, Profile]>>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'starUser' : ActorMethod<[Principal], undefined>,
  'tinderLike' : ActorMethod<[Principal], undefined>,
  'tinderPass' : ActorMethod<[Principal], undefined>,
  'unfollow' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];