/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'interests' : IDL.Text,
  'education' : IDL.Text,
  'website' : IDL.Text,
  'coverPhoto' : IDL.Opt(ExternalBlob),
  'birthday' : IDL.Text,
  'gender' : IDL.Text,
  'favSongs' : IDL.Text,
  'thoughts' : IDL.Text,
  'favMovies' : IDL.Text,
  'location' : IDL.Text,
  'hobbies' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
  'relationshipStatus' : IDL.Text,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const PostDTO = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
  'comments' : IDL.Vec(Comment),
});
export const Message = IDL.Record({
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'timestamp' : Time,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'kind' : IDL.Text,
  'read' : IDL.Bool,
  'timestamp' : Time,
  'fromUser' : IDL.Principal,
  'targetId' : IDL.Nat,
});
export const Story = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRequest' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'commentOnPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'createProfile' : IDL.Func([Profile], [], []),
  'createStory' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'follow' : IDL.Func([IDL.Principal], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(PostDTO)], ['query']),
  'getAllProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(PostDTO)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getStarsReceived' : IDL.Func([], [IDL.Nat], ['query']),
  'getStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'getStoryHighlights' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'getTinderQueue' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'saveStoryToHighlight' : IDL.Func([IDL.Nat], [], []),
  'searchUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'starUser' : IDL.Func([IDL.Principal], [], []),
  'tinderLike' : IDL.Func([IDL.Principal], [], []),
  'tinderPass' : IDL.Func([IDL.Principal], [], []),
  'unfollow' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'interests' : IDL.Text,
    'education' : IDL.Text,
    'website' : IDL.Text,
    'coverPhoto' : IDL.Opt(ExternalBlob),
    'birthday' : IDL.Text,
    'gender' : IDL.Text,
    'favSongs' : IDL.Text,
    'thoughts' : IDL.Text,
    'favMovies' : IDL.Text,
    'location' : IDL.Text,
    'hobbies' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
    'relationshipStatus' : IDL.Text,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const PostDTO = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'comments' : IDL.Vec(Comment),
  });
  const Message = IDL.Record({
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'timestamp' : Time,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'kind' : IDL.Text,
    'read' : IDL.Bool,
    'timestamp' : Time,
    'fromUser' : IDL.Principal,
    'targetId' : IDL.Nat,
  });
  const Story = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRequest' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'commentOnPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'createProfile' : IDL.Func([Profile], [], []),
    'createStory' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'follow' : IDL.Func([IDL.Principal], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(PostDTO)], ['query']),
    'getAllProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(PostDTO)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getStarsReceived' : IDL.Func([], [IDL.Nat], ['query']),
    'getStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
    'getStoryHighlights' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getTinderQueue' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'saveStoryToHighlight' : IDL.Func([IDL.Nat], [], []),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'starUser' : IDL.Func([IDL.Principal], [], []),
    'tinderLike' : IDL.Func([IDL.Principal], [], []),
    'tinderPass' : IDL.Func([IDL.Principal], [], []),
    'unfollow' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };